services:
  postgres:
    restart: always

  redis:
    restart: always

  backend:
    restart: always
    command: ["sh", "-c", "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2"]

  notification:
    restart: always

  evolution:
    restart: always

  frontend:
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: https://app.sabiadeveloper.com/api

  nginx:
    profiles:
      - disabled
